spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:flyway_demo_dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/dev
    clean-disabled: false  # Allow clean in development